import type { AdapterCertificationResult, AdapterCertificationCaseResult } from "./conformanceSchema.js";

function statusBadge(result: AdapterCertificationCaseResult): string {
  if (result.passed) return result.warnings.length > 0 ? "WARN" : "PASS";
  return "FAIL";
}

function certBadge(status: string): string {
  if (status === "pass") return "PASS";
  if (status === "passed_with_warnings") return "PASS (warnings)";
  return "FAIL";
}

// ── Text ─────────────────────────────────────────────────────────────────────

export function generateCertificationText(result: AdapterCertificationResult): string {
  const lines: string[] = [
    `AgentShield Adapter Conformance: ${certBadge(result.certificationStatus)}`,
    `Adapter: ${result.adapterName} (${result.adapterId})`,
    `Suite: ${result.suiteName}`,
    `Cases: ${result.passed}/${result.total} passed`
  ];

  if (result.warnings > 0) {
    lines.push(`Warnings: ${result.warnings}`);
  }

  lines.push("");

  for (const caseItem of result.cases) {
    const badge = statusBadge(caseItem);
    lines.push(`  ${badge} ${caseItem.name}`);
    for (const failure of caseItem.failures) {
      lines.push(`       - ${failure}`);
    }
    for (const warning of caseItem.warnings) {
      lines.push(`       ~ ${warning}`);
    }
  }

  if (result.certificationFailures.length > 0) {
    lines.push("");
    lines.push("Certification failures:");
    for (const failure of result.certificationFailures) {
      lines.push(`  - ${failure}`);
    }
  }

  return lines.join("\n");
}

// ── JSON ──────────────────────────────────────────────────────────────────────

export function generateCertificationJson(result: AdapterCertificationResult): string {
  return JSON.stringify(result, null, 2);
}

// ── Markdown ──────────────────────────────────────────────────────────────────

export function generateCertificationMarkdown(result: AdapterCertificationResult): string {
  const lines: string[] = [
    "# AgentShield Adapter Conformance Report",
    "",
    `**Adapter:** ${result.adapterName} (\`${result.adapterId}\`)`,
    `**Suite:** ${result.suiteName}`,
    `**Status:** ${certBadge(result.certificationStatus)}`,
    `**Cases:** ${result.passed}/${result.total} passed`,
    ""
  ];

  if (result.certificationFailures.length > 0) {
    lines.push("## Certification Failures", "");
    for (const failure of result.certificationFailures) {
      lines.push(`- ${failure}`);
    }
    lines.push("");
  }

  lines.push("## Case Results", "");
  lines.push("| # | Case | Status | Decision | Forwarded | Execution | Failures |");
  lines.push("| --- | --- | --- | --- | --- | --- | --- |");

  result.cases.forEach((caseItem, index) => {
    const badge = statusBadge(caseItem);
    const decision = caseItem.decision ?? "—";
    const forwarded = caseItem.forwarded === undefined ? "—" : String(caseItem.forwarded);
    const executionStatus = caseItem.executionStatus ?? "—";
    const failures = caseItem.failures.length > 0 ? caseItem.failures.join("; ") : "none";
    lines.push(`| ${index + 1} | ${caseItem.name} | ${badge} | ${decision} | ${forwarded} | ${executionStatus} | ${failures} |`);
  });

  lines.push("");
  lines.push("---");
  lines.push("");
  lines.push(`_Generated by AgentShield Veritas. Certification is local and deterministic._`);

  return lines.join("\n");
}
