import { defaultAttackScenarios, registryAttackScenarios } from "./fixtures/index.js";
import { generateHtmlReport } from "./report/htmlReport.js";
import { generateJsonReport } from "./report/jsonReport.js";
import { generateMarkdownReport } from "./report/markdownReport.js";
import { generateMatrixReport } from "./report/matrixReport.js";
import { generateScorecard } from "./report/scorecard.js";
import { runBenchmarkScenarios, type BenchmarkRunnerOptions } from "./runner/benchmarkRunner.js";
import type { ScoringProfileName } from "./scoring/scoringProfile.js";

export * from "./recipes/recipeSchema.js";
export * from "./recipes/builtInRecipes.js";
export * from "./recipes/recipeValidator.js";
export * from "./recipes/recipeControlMatrix.js";
export * from "./recipes/recipeDoctor.js";
export * from "./recipes/recipeReport.js";
export * from "./multiAgent/multiAgentReport.js";
export * from "./ide/ideIntegrationSchema.js";
export * from "./ide/vscodeTaskGenerator.js";
export * from "./ide/diagnosticMapping.js";
export * from "./ide/idePanelReport.js";
export * from "./ide/ideDoctor.js";
export * from "./releaseCandidate/releaseCandidateManifest.js";
export * from "./releaseCandidate/releaseReadinessScore.js";
export * from "./releaseCandidate/releaseCandidateChecklist.js";
export * from "./releaseCandidate/releaseCandidateReport.js";
export * from "./releaseCandidate/releaseNotesGenerator.js";
export * from "./releaseCandidate/releaseArtifactInventory.js";
export * from "./supplyChain/packageIntegritySchema.js";
export * from "./supplyChain/supplyChainReport.js";
export * from "./releaseCandidate/generatedFileCleanupCheck.js";
export * from "./incident/incidentReport.js";
export * from "./corpus/corpusIndex.js";
export * from "./corpus/corpusMetadata.js";
export * from "./corpus/corpusValidator.js";
export * from "./ci/ciConfig.js";
export * from "./ci/ciExitStatus.js";
export * from "./ci/ciGate.js";
export * from "./fixtures/index.js";
export * from "./perf/latencyBudget.js";
export * from "./perf/perfReport.js";
export * from "./registryBundle/registryBundleReport.js";
export * from "./perf/perfRunner.js";
export * from "./perf/perfTimer.js";
export * from "./auditor/auditorEvidencePackSchema.js";
export * from "./auditor/auditorEvidenceHash.js";
export * from "./auditor/auditorEvidenceCollector.js";
export * from "./auditor/auditorEvidenceReport.js";
export * from "./auditor/auditorEvidenceVerifier.js";
export * from "./sensitive/sensitiveScanReport.js";
export * from "./policyAudit/policyAuditReport.js";
export * from "./policyAudit/policyAuditRunner.js";
export * from "./policyAudit/policyAuditSchema.js";
export * from "./policyAudit/policyConflictDetector.js";
export * from "./policyAudit/policyCoverageAnalyzer.js";
export * from "./policyPack/builtInPolicyPacks.js";
export * from "./policyPack/policyPackRenderer.js";
export * from "./policyPack/policyPackReport.js";
export * from "./policyPack/policyPackSchema.js";
export * from "./policyPack/policyPackValidator.js";
export * from "./policyTest/policyTestReport.js";
export * from "./policyTest/policyTestRunner.js";
export * from "./attackGraphExplain/attackGraphExplainReport.js";
export * from "./policyTest/policyTestSchema.js";
export * from "./policyTest/policyTestSnapshot.js";
export * from "./policyTemplate/builtInPolicyTemplates.js";
export * from "./policyTemplate/policyTemplateRenderer.js";
export * from "./policyTemplate/policyTemplateReport.js";
export * from "./policyTemplate/policyTemplateSchema.js";
export * from "./redteam/redteamCoverage.js";
export * from "./redteam/redteamGenerator.js";
export * from "./redteam/redteamMutations.js";
export * from "./redteam/redteamReport.js";
export * from "./redteam/redteamTemplateSchema.js";
export * from "./policyBundle/policyBundleReport.js";
export * from "./securityFuzz/deterministicMutations.js";
export * from "./securityFuzz/failureModeSchema.js";
export * from "./securityFuzz/securityFuzzFixtures.js";
export * from "./securityFuzz/securityFuzzReport.js";
export * from "./securityFuzz/securityFuzzRunner.js";
export * from "./report/htmlReport.js";
export * from "./report/jsonReport.js";
export * from "./report/markdownReport.js";
export * from "./report/matrixReport.js";
export * from "./registryBundle/registryBundleReport.js";
export * from "./report/regressionSnapshot.js";
export * from "./report/sarifReport.js";
export * from "./report/scorecard.js";
export * from "./runner/benchmarkRunner.js";
export * from "./scenario/attackScenario.js";
export * from "./scoring/categoryBreakdown.js";
export * from "./scoring/scoringProfile.js";
export * from "./scoring/weightedScore.js";
export * from "./consumer/consumerProjectSchema.js";
export * from "./consumer/consumerValidator.js";
export * from "./consumer/consumerEvaluationRunner.js";
export * from "./consumer/consumerEvaluationReport.js";
export * from "./consumer/publicEvaluationPack.js";
export * from "./leaderboard/leaderboardResultSchema.js";
export * from "./leaderboard/leaderboardEntrySchema.js";
export * from "./leaderboard/benchmarkSubmissionManifest.js";
export * from "./leaderboard/scoreNormalizer.js";
export * from "./leaderboard/corpusVersionPinning.js";
export * from "./leaderboard/leaderboardResultHash.js";
export * from "./leaderboard/leaderboardVerifier.js";
export * from "./leaderboard/leaderboardReport.js";
export * from "./governance/governanceRecordSchema.js";
export * from "./governance/governanceValidator.js";
export * from "./governance/governanceReport.js";
export * from "./governance/submissionSafety.js";
export * from "./governance/maintainerChecklist.js";
export * from "./marketplace/marketplaceEntrySchema.js";
export * from "./marketplace/marketplaceIndexSchema.js";
export * from "./marketplace/policyPackTrustReview.js";
export * from "./marketplace/marketplaceSafetyScore.js";
export * from "./marketplace/marketplaceValidator.js";
export * from "./marketplace/marketplaceReviewReport.js";
export * from "./marketplace/marketplaceInstallPlan.js";


export function runDefaultBenchmark(profile: ScoringProfileName = "balanced", options: BenchmarkRunnerOptions = {}) {
  const scenarios = options.toolRegistry === undefined ? defaultAttackScenarios : [...defaultAttackScenarios, ...registryAttackScenarios];
  return generateScorecard(runBenchmarkScenarios(scenarios, options), profile);
}

export function runBenchCommand(format: "json" | "html" | "markdown" | "matrix" = "json", profile: ScoringProfileName = "balanced"): string {
  const scorecard = runDefaultBenchmark(profile);
  if (format === "html") return generateHtmlReport(scorecard);
  if (format === "markdown") return generateMarkdownReport(scorecard);
  if (format === "matrix") return generateMatrixReport(scorecard);
  return generateJsonReport(scorecard);
}
export * from "./docsNavigator/docsManifestSchema.js";
export * from "./docsNavigator/docsNavigationSchema.js";
export * from "./docsNavigator/docsIntegrityValidator.js";
export * from "./docsNavigator/docsFeatureCoverage.js";
export * from "./docsNavigator/docsCommandCatalog.js";
export * from "./docsNavigator/docsMapReport.js";
export * from "./corpusV4/corpusScenarioMetadata.js";
export * from "./corpusV4/scenarioProvenance.js";
export * from "./corpusV4/scenarioDifficulty.js";
export * from "./corpusV4/corpusData.js";
export * from "./corpusV4/corpusQualityGate.js";
export * from "./corpusV4/corpusCoverageMap.js";
export * from "./corpusV4/corpusRegressionSnapshot.js";
export * from "./corpusV4/corpusReport.js";
export * from "./perfBaseline/index.js";
export * from "./securityReview/securityReviewPackSchema.js";
export * from "./securityReview/securityClaimsBoundary.js";
export * from "./securityReview/reviewScope.js";
export * from "./securityReview/evidenceIndex.js";
export * from "./securityReview/reviewTestMatrix.js";
export * from "./securityReview/invariantCoverageMap.js";
export * from "./securityReview/auditFindingSchema.js";
export * from "./securityReview/remediationTracker.js";
export * from "./securityReview/securityReviewReport.js";

export * from "./v1Readiness/index.js";
export * from "./publicRc/index.js";
